### ISSUE TITLE
AssertionError: Command raised an exception: AssertionError: 

### ISSUE THREAD

**Issue by pogblob** [HexCodeFFF/mediaforge#115]
DATETIME:2022-07-29 14:59:40.858577
COMMAND:$download https://www.youtube.com/watch?v=KcTWA-hhubI
TRACEBACK:
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.8/lib/python3.8/site-packages/nextcord/ext/commands/core.py", line 165, in wrapped
    ret = await coro(*args, **kwargs)
  File "/mediaforge/cog_conversion.py", line 111, in videodl
    r = await improcessing.assurefilesize(r, ctx, re_encode=False)
  File "/mediaforge/improcessing.py", line 398, in assurefilesize
    raise e
  File "/mediaforge/improcessing.py", line 393, in assurefilesize
    video = await twopasscapvideo(media, config.file_upload_limit)
  File "/mediaforge/improcessing.py", line 318, in twopasscapvideo
    assert target_video_bitrate > 0
AssertionError

**Comment by HexCodeFFF** [comment]
I've seen this error before, it appears to be unable to determine the ideal bitrate. I'll have to check what's going wrong.

**Comment by HexCodeFFF** [comment]
alright i have it raise a more human readable error now
