### ISSUE TITLE
$download command not downloading videos

### ISSUE THREAD

**Issue by baguttecunsumer** [HexCodeFFF/mediaforge#152]
### Describe the bug

when I do the $download command and then put in a video it doesn't download and says

```DATETIME:2023-01-20 20:27:52.196181
COMMAND:$download https://quickvids.win/AfmcGHB5
TRACEBACK:
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/concurrent/futures/process.py", line 212, in _sendback_result
    result_queue.put(_ResultItem(work_id, result=result,
  File "/usr/local/lib/python3.11/multiprocessing/queues.py", line 371, in put
    obj = _ForkingPickler.dumps(obj)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle '_io.BufferedReader' object
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/commands/conversion.py", line 102, in videodl
    r = await run_parallel(ytdownload, videourl, videoformat)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/processing/common.py", line 120, in run_parallel
    success, res, files = await asyncio.get_running_loop().run_in_executor(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot pickle '_io.BufferedReader' object

### Traceback

TRACEBACK:
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/concurrent/futures/process.py", line 212, in _sendback_result
    result_queue.put(_ResultItem(work_id, result=result,
  File "/usr/local/lib/python3.11/multiprocessing/queues.py", line 371, in put
    obj = _ForkingPickler.dumps(obj)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle '_io.BufferedReader' object
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/commands/conversion.py", line 102, in videodl
    r = await run_parallel(ytdownload, videourl, videoformat)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/processing/common.py", line 120, in run_parallel
    success, res, files = await asyncio.get_running_loop().run_in_executor(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^```

### Expected Behavior

it to download and send in video

### Steps To Reproduce

/tiktok on QuickVids discord bot put in the link from that to the mediaforge bot
$download https://quickvids.win/whatever
no video

### Anything Else

![image](https://user-images.githubusercontent.com/123209131/213803649-89f3e95c-fc67-4edd-8295-1c58c243f696.png)

**Comment by baguttecunsumer** [comment]
thx for the help guys 👍

**Comment by HexCodeFFF** [comment]
No need to be an ass
I’m busy I have things to do that aren’t funny discord bot 
I’m aware of the issue and I’ll fix it at some poibt

**Comment by Wolfhound905** [comment]
Hey, it's not a funny discord bot 😒

/j (I'm the creator)
