### ISSUE TITLE
$twemoji not working - LookupError: Command raised an exception: LookupError: <ContextVar name='session' at 0x7f0d062e26b0>

### ISSUE THREAD

**Issue by OffensiveLemon** [HexCodeFFF/mediaforge#170]
When I try to use $twemoji, I get the following error:

`LookupError: Command raised an exception: LookupError: <ContextVar name='session' at 0x7f0d062e26b0>`
```
DATETIME:2023-05-04 14:45:54.732178
COMMAND:$twemoji 😭
TRACEBACK:
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/commands/conversion.py", line 246, in twemoji
    await asyncio.gather(*[upload_url(url) for url in urls])
  File "/mediaforge/src/commands/conversion.py", line 241, in upload_url
    await ctx.reply(file=discord.File(await utils.web.saveurl(url)))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/utils/web.py", line 28, in saveurl
    name = reserve_tempfile(extension)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/utils/tempfiles.py", line 58, in reserve_tempfile
    tfs = session.get()
          ^^^^^^^^^^^^^
LookupError: <ContextVar name='session' at 0x7f0d062e26b0>
```

**Comment by HexCodeFFF** [comment]
oh i think i know what is wrong here hold on should be a quick fix

**Comment by OffensiveLemon** [comment]
Cool, thanks
