### ISSUE TITLE
Instagram reels wont download anymore

### ISSUE THREAD

**Issue by beans0256** [HexCodeFFF/mediaforge#174]

**Comment by beans0256** [comment]
Error log given: 

DATETIME:2023-05-15 23:50:53.952355
COMMAND:$videodl https://www.instagram.com/reel/CpVuwTnpIi6/?igshid=MzRlODBiNWFlZA
TRACEBACK:
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/concurrent/futures/process.py", line 212, in _sendback_result
    result_queue.put(_ResultItem(work_id, result=result,
  File "/usr/local/lib/python3.11/multiprocessing/queues.py", line 371, in put
    obj = _ForkingPickler.dumps(obj)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle '_io.BufferedReader' object
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/commands/conversion.py", line 102, in videodl
    r = await run_parallel(ytdownload, videourl, videoformat)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/processing/common.py", line 120, in run_parallel
    success, res, files = await asyncio.get_running_loop().run_in_executor(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot pickle '_io.BufferedReader' object

**Comment by HexCodeFFF** [comment]
Can you send a URL of a reel that causes this so I can test it?

**Comment by HexCodeFFF** [comment]
I'm stupid it was in the traceback
Anyways I updated https://github.com/yt-dlp/yt-dlp recently and it seems to be fixed so I'm closing this
