### ISSUE TITLE
Ffmpeg: invalid fastbin entry (free)

### ISSUE THREAD

**Issue by frutasfnf** [HexCodeFFF/mediaforge#201]
### Describe the bug

Tried to caption a gif, then this error occurred.

### Traceback

```
DATETIME:2023-08-16 00:50:57.486050
COMMAND:$cap run that back
TRACEBACK:
processing.common.CMDError: ffmpeg version N-111626-g0ba719f726 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/root/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/root/ffmpeg_build/include --extra-ldflags=-L/root/ffmpeg_build/lib --extra-libs='-lpthread -lm' --ld=g++ --bindir=/usr/local/bin --enable-gpl --enable-gnutls --enable-libaom --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libsvtav1 --enable-libdav1d --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      58. 14.100 / 58. 14.100
  libavcodec     60. 22.100 / 60. 22.100
  libavformat    60. 10.100 / 60. 10.100
  libavdevice    60.  2.101 / 60.  2.101
  libavfilter     9. 10.100 /  9. 10.100
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Input #0, png_pipe, from '/dev/shm/mediaforge/NkpFkOte.png':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: png, rgba(pc, gbr/unknown/unknown), 1200x201 [SAR 2835:2835 DAR 400:67], 25 fps, 25 tbr, 25 tbn
Input #1, gif, from '/dev/shm/mediaforge/WYVShOIJ.gif':
  Metadata:
    comment         : Created with ezgif.com GIF maker
  Duration: 00:00:00.91, start: 0.000000, bitrate: 7119 kb/s
  Stream #1:0: Video: gif, bgra, 1200x1171, 14.29 fps, 28.58 tbr, 100 tbn
Stream mapping:
  Stream #0:0 (png) -> format:default
  Stream #1:0 (gif) -> format:default
  vstack:default -> Stream #0:0 (png)
Press [q] to stop, [?] for help
invalid fastbin entry (free)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/commands/caption.py", line 115, in captioncommand
    await process(ctx, processing.vips.vipsutils.generic_caption_stack, [["VIDEO", "GIF", "IMAGE"]],
  File "/mediaforge/src/core/process.py", line 151, in process
    raise e
  File "/mediaforge/src/core/process.py", line 121, in process
    result = await queue.enqueue(run())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/core/queue.py", line 26, in enqueue
    raise e
  File "/mediaforge/src/core/queue.py", line 23, in enqueue
    res = await task
          ^^^^^^^^^^
  File "/mediaforge/src/core/process.py", line 107, in run
    command_result = await func(*args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/processing/vips/vipsutils.py", line 23, in generic_caption_stack
    return await processing.ffmpeg.naive_vstack(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/processing/ffmpeg.py", line 560, in naive_vstack
    await run_command("ffmpeg", "-i", file0, "-i", file1, "-filter_complex",
  File "/mediaforge/src/processing/common.py", line 75, in run_command
    raise CMDError(f"Command {args} failed.") from CMDError(result)
processing.common.CMDError: Command ('ffmpeg', '-i', '/dev/shm/mediaforge/NkpFkOte.png', '-i', '/dev/shm/mediaforge/WYVShOIJ.gif', '-filter_complex', '[0]format=pix_fmts=yuva420p[0f];[1]format=pix_fmts=yuva420p[1f];[0f][1f]vstack=inputs=2', '-c:v', 'png', '-fs', '1G', '-fps_mode', 'vfr', '/dev/shm/mediaforge/ILYBrPuc.mp4') failed.
```

### Expected Behavior

Expected a captioned gif

**Comment by HexCodeFFF** [comment]
consolidating this under #147
