### ISSUE TITLE
Command 'imagesay' raised an exception: Forbidden: 403 Forbidden (error code: 50001): Missing Access

### ISSUE THREAD

**Issue by SwenLdn** [HexCodeFFF/mediaforge#214]
### Describe the bug

discord.app_commands.errors.CommandInvokeError: Hybrid command raised an error: Command 'imagesay' raised an exception: Forbidden: 403 Forbidden (error code: 50001): Missing Access

### Traceback
```
DATETIME:2023-10-11 14:15:36.568451
COMMAND:/imagesay {'text': 'a group of Brazilian stupid but lovable young macho man and a man dressed as a woman in silly maid uniform sleep with eyes closed in kitchen on furniture among empty liquior bottles, cigarette smoke, whimsical scene of party hangover, bold colours, whimsical facial expression and posture, she is the boss 8k --ar 16:9'}
TRACEBACK:
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/commands/image.py", line 83, in imagesay
    await process(ctx, processing.vips.caption.generic_image_caption, [["IMAGE"]],
  File "/mediaforge/src/core/process.py", line 151, in process
    raise e
  File "/mediaforge/src/core/process.py", line 62, in process
    urls = await imagesearch(ctx, len(inputs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/utils/scandiscord.py", line 82, in imagesearch
    async for m in ctx.channel.history(limit=50, before=ctx.message):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/abc.py", line 1804, in history
    data, state, limit = await strategy(retrieve, state, limit)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/abc.py", line 1746, in _before_strategy
    data = await self._state.http.logs_from(channel.id, retrieve, before=before_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/http.py", line 739, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'imagesay' raised an exception: Forbidden: 403 Forbidden (error code: 50001): Missing Access
```

**Comment by HexCodeFFF** [comment]
Does the bot have message history permissions in the channel you ran it in?
