### ISSUE TITLE
$addaudio doesn't work

### ISSUE THREAD

**Issue by MERRIT2** [HexCodeFFF/mediaforge#37]
It always has worked before, it started not working yesterday.
This is the copy paste of the error message:

IndexError: Command raised an exception: IndexError: list index out of range

DATETIME:2021-09-27 21:43:06.621508
COMMAND:$addaudio
TRACEBACK:
Traceback (most recent call last):
  File "/home/hex/.local/share/virtualenvs/captionbot-iutiqbOm/lib/python3.8/site-packages/nextcord/ext/commands/core.py", line 168, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 758, in addaudio
    await improcess(ctx, improcessing.addaudio, [["IMAGE", "GIF", "VIDEO", "AUDIO"], ["AUDIO"]])
  File "main.py", line 428, in improcess
    if await improcessing.is_apng(file):
  File "/home/hex/Desktop/captionbot/improcessing.py", line 157, in is_apng
    return data["streams"][0]["codec_name"] == "apng"
IndexError: list index out of range

**Comment by HexCodeFFF** [comment]
Ah shit I see the issue 

Super simple fix, gimme a minute hhhhhh
