### ISSUE TITLE
$help | [Errno 32] Broken pipe 

### ISSUE THREAD

**Issue by Marchay** [HexCodeFFF/mediaforge#49]
Happened when using $help

```
DATETIME:2021-12-30 15:32:13.215997
COMMAND:$help
TRACEBACK:
Traceback (most recent call last):
  File "/home/hex/.local/share/virtualenvs/captionbot-iutiqbOm/lib/python3.8/site-packages/nextcord/ext/commands/core.py", line 168, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 1979, in help
    await ctx.reply(embed=embed)
  File "/home/hex/.local/share/virtualenvs/captionbot-iutiqbOm/lib/python3.8/site-packages/nextcord/ext/commands/context.py", line 400, in reply
    return await self.message.reply(content, **kwargs)
  File "main.py", line 70, in safe_reply
    return await self.orig_reply(*args, **kwargs)
  File "/home/hex/.local/share/virtualenvs/captionbot-iutiqbOm/lib/python3.8/site-packages/nextcord/message.py", line 1564, in reply
    return await self.channel.send(content, reference=self, **kwargs)
  File "/home/hex/.local/share/virtualenvs/captionbot-iutiqbOm/lib/python3.8/site-packages/nextcord/abc.py", line 1422, in send
    data = await state.http.send_message(
  File "/home/hex/.local/share/virtualenvs/captionbot-iutiqbOm/lib/python3.8/site-packages/nextcord/http.py", line 273, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/home/hex/.local/share/virtualenvs/captionbot-iutiqbOm/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/hex/.local/share/virtualenvs/captionbot-iutiqbOm/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/home/hex/.local/share/virtualenvs/captionbot-iutiqbOm/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/home/hex/.local/share/virtualenvs/captionbot-iutiqbOm/lib/python3.8/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe
```
![image](https://user-images.githubusercontent.com/40936964/147789725-349b58a6-f774-48b4-b04f-952a70225af2.png)

**Comment by HexCodeFFF** [comment]
I think this is just a regular connection issue because the pc running mediaforge is cheap so it gets regularly overwhelmed
