### ISSUE TITLE
aiohttp.client_exceptions.ClientOSError: Command raised an exception: ClientOSError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by enchanted-sword** [HexCodeFFF/mediaforge#53]
Happened while trying to vertically stack a gif and a static image

```DATETIME:2022-01-02 18:23:49.632297
COMMAND:$vstack
TRACEBACK:
Traceback (most recent call last):
  File "/home/hex/.local/share/virtualenvs/captionbot-iutiqbOm/lib/python3.8/site-packages/nextcord/ext/commands/core.py", line 168, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 1130, in vstack
    await improcess(ctx, improcessing.stack, [["VIDEO", "GIF", "IMAGE"], ["VIDEO", "GIF", "IMAGE"]],
  File "main.py", line 443, in improcess
    urls = await imagesearch(ctx, len(allowedtypes))
  File "main.py", line 303, in imagesearch
    hm = await handlemessagesave(m)
  File "main.py", line 248, in handlemessagesave
    tenor = await fetch(
  File "/home/hex/Desktop/captionbot/improcessing.py", line 1430, in fetch
    async with session.get(url) as response:
  File "/home/hex/.local/share/virtualenvs/captionbot-iutiqbOm/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/hex/.local/share/virtualenvs/captionbot-iutiqbOm/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/home/hex/.local/share/virtualenvs/captionbot-iutiqbOm/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/home/hex/.local/share/virtualenvs/captionbot-iutiqbOm/lib/python3.8/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe```

**Comment by HexCodeFFF** [comment]
Hmm I've seen this error a lot and I'm not sure what causes it but it appears to be one-time so a possible fix would be to implement code to retry a couple times

**Comment by HexCodeFFF** [comment]
If you're able to find a way to reliably reproduce it I'd love to see it

**Comment by HexCodeFFF** [comment]
Seems to be related to #49

**Comment by enchanted-sword** [comment]
Funnily enough I tried it earlier as well and got a different error message

**Comment by HexCodeFFF** [comment]
Can you upload that error message?

**Comment by enchanted-sword** [comment]
`DATETIME:2022-01-02 17:06:26.783697
COMMAND:$vstack
TRACEBACK:
Traceback (most recent call last):
  File "/home/hex/.local/share/virtualenvs/captionbot-iutiqbOm/lib/python3.8/site-packages/nextcord/ext/commands/core.py", line 168, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 1130, in vstack
    await improcess(ctx, improcessing.stack, [["VIDEO", "GIF", "IMAGE"], ["VIDEO", "GIF", "IMAGE"]],
  File "main.py", line 444, in improcess
    files = await saveurls(urls)
  File "main.py", line 369, in saveurls
    files.append(await saveurl(url))
  File "main.py", line 332, in saveurl
    async with session.get(url) as resp:
  File "/home/hex/.local/share/virtualenvs/captionbot-iutiqbOm/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/hex/.local/share/virtualenvs/captionbot-iutiqbOm/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/home/hex/.local/share/virtualenvs/captionbot-iutiqbOm/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/home/hex/.local/share/virtualenvs/captionbot-iutiqbOm/lib/python3.8/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError`

**Comment by HexCodeFFF** [comment]
Hmm this seems to just be an internet issue. I might try to see if I can get it to auto retry or just have a generic "try again later" error.
