### ISSUE TITLE
idk what this is, but this happened when i pinged the bot for help

### ISSUE THREAD

**Issue by AHHHHHHHHHHHHHHHHHHHHHHsrb2** [HexCodeFFF/mediaforge#58]
DATETIME:2022-02-04 20:23:06.523526
COMMAND:<@!780570413767983122> help
TRACEBACK:
Traceback (most recent call last):
  File "/home/hex/.cache/pypoetry/virtualenvs/mediaforge-4kydknjC-py3.8/lib/python3.8/site-packages/nextcord/ext/commands/core.py", line 168, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 1992, in help
    await ctx.reply(embed=embed)
  File "/home/hex/.cache/pypoetry/virtualenvs/mediaforge-4kydknjC-py3.8/lib/python3.8/site-packages/nextcord/ext/commands/context.py", line 400, in reply
    return await self.message.reply(content, **kwargs)
  File "main.py", line 68, in safe_reply
    await self.channel.fetch_message(self.id)
  File "/home/hex/.cache/pypoetry/virtualenvs/mediaforge-4kydknjC-py3.8/lib/python3.8/site-packages/nextcord/abc.py", line 1497, in fetch_message
    data = await self._state.http.get_message(channel.id, id)
  File "/home/hex/.cache/pypoetry/virtualenvs/mediaforge-4kydknjC-py3.8/lib/python3.8/site-packages/nextcord/http.py", line 275, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/home/hex/.cache/pypoetry/virtualenvs/mediaforge-4kydknjC-py3.8/lib/python3.8/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/home/hex/.cache/pypoetry/virtualenvs/mediaforge-4kydknjC-py3.8/lib/python3.8/site-packages/aiohttp/client.py", line 634, in _request
    break
  File "/home/hex/.cache/pypoetry/virtualenvs/mediaforge-4kydknjC-py3.8/lib/python3.8/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

**Comment by HexCodeFFF** [comment]
More errors from the bot being overloaded. I'll see if I can add a fix so it doesn't error out but in the meantime just try again in a bit.
