### ISSUE TITLE
expected str, bytes or os.PathLike object, not NoneType on run_command()

### ISSUE THREAD

**Issue by Esoterit** [HexCodeFFF/mediaforge#72]
Using $esmcaption (likely in succession while multiple gifs are being processed) causes this error. Nothing extraordinary was done to reproduce this error except have another gif posted while a previous one is being processed. This is not guaranteed to reproduce the error.
Here is the stacktrace.
DATETIME:2022-03-03 02:06:49.925513
COMMAND:$esmcaption Resulting file too big! (59.4 MB) Downsizing result...
TRACEBACK:
Traceback (most recent call last):
  File "/home/hex/.cache/pypoetry/virtualenvs/mediaforge-4kydknjC-py3.8/lib/python3.8/site-packages/nextcord/ext/commands/core.py", line 168, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 769, in esmcaption
    await improcess(ctx, captionfunctions.esmcaption, [["VIDEO", "GIF", "IMAGE"]], caption, handleanimated=True)
  File "main.py", line 516, in improcess
    raise e
  File "main.py", line 505, in improcess
    await improcessing.watermark(result)
  File "/home/hex/Desktop/captionbot/improcessing.py", line 469, in watermark
    if (await mediatype(media)) == "AUDIO":  # exiftool doesnt support it :/
  File "/home/hex/Desktop/captionbot/improcessing.py", line 490, in mediatype
    probe = await run_command('ffprobe', '-v', 'panic', '-count_packets', '-show_entries',
  File "/home/hex/Desktop/captionbot/improcessing.py", line 133, in run_command
    process = await asyncio.create_subprocess_exec(
  File "/usr/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.8/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/lib/python3.8/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1639, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not NoneType
![SucXpcNN](https://user-images.githubusercontent.com/93238539/156527196-e6d8b373-7e7d-4b5f-b5fa-ffbf59ce8310.gif)

**Comment by HexCodeFFF** [comment]
The issue appears to be coming from the new buggy media type detection, but the error is very strange. You said that this only occurs when captioning gifs in rapid succession? If there is *any* single gif/other media that reliably reproduces this error, could you upload it?
