### ISSUE TITLE
[Errno 32] Broken pipe

### ISSUE THREAD

**Issue by 6vz** [HexCodeFFF/mediaforge#80]
**Describe the bug**
Broken Pipe

**To Reproduce**
- Upload video
- [p]caption it
- done

**Expected behavior**
should return video with caption, not with error

**Traceback**
```DATETIME:2022-03-20 12:55:06.017960
COMMAND:media.caption me on the way to ddos & destroy & fry this server
TRACEBACK:
Traceback (most recent call last):
  File "/home/hex/.cache/pypoetry/virtualenvs/mediaforge-4kydknjC-py3.8/lib/python3.8/site-packages/nextcord/ext/commands/core.py", line 168, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 697, in captioncommand
    await improcess(ctx, captionfunctions.caption, [["VIDEO", "GIF", "IMAGE"]], caption, handleanimated=True)
  File "main.py", line 458, in improcess
    files = await saveurls(urls)
  File "main.py", line 383, in saveurls
    files.append(await saveurl(url))
  File "main.py", line 346, in saveurl
    async with session.get(url) as resp:
  File "/home/hex/.cache/pypoetry/virtualenvs/mediaforge-4kydknjC-py3.8/lib/python3.8/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/home/hex/.cache/pypoetry/virtualenvs/mediaforge-4kydknjC-py3.8/lib/python3.8/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/home/hex/.cache/pypoetry/virtualenvs/mediaforge-4kydknjC-py3.8/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/home/hex/.cache/pypoetry/virtualenvs/mediaforge-4kydknjC-py3.8/lib/python3.8/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe```

**Comment by HexCodeFFF** [comment]
Standard hosting issue. Try again shortly. Ill work on a more user friendly error.
