### ISSUE TITLE
Command ('ffmpeg', '-i', 'temp/tBnVSsME.mov', '-pix_fmt', 'yuva420p', '-max_muxing_queue_size', '9999', '-sws_flags', 'spline+accurate_rnd+full_chroma_int+full_chroma_inp+bitexact', '-vf', "scale='1500:-1',setsar=1:1", '-c:v', 'png', '-pix_fmt', 'yuva420p', '-c:a', 'copy', 'temp/lMhAnAMp.mp4') failed.

### ISSUE THREAD

**Issue by spy-ware** [HexCodeFFF/mediaforge#98]

**Comment by spy-coding** [comment]
```
DATETIME:2022-05-14 22:54:26.714795
COMMAND:?reencode
TRACEBACK:
improcessing.CMDError: ffmpeg version 5.0.1-1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11 (Debian 11.2.0-19)
  configuration: --prefix=/usr --extra-version=1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libplacebo --enable-libx264 --enable-shared
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'temp/tBnVSsME.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 512
    compatible_brands: qt  
    creation_time   : 2022-05-14T22:52:41.000000Z
  Duration: 00:00:08.54, start: 0.000000, bitrate: 6009 kb/s
  Stream #0:0[0x1]: Video: h264 (Main) (avc1 / 0x31637661), yuv420p(bt709, progressive), 1920x1080, 4470 kb/s, SAR 1:1 DAR 16:9, 24 fps, 24 tbr, 12288 tbn (default)
    Metadata:
      creation_time   : 2022-05-14T22:52:41.000000Z
      handler_name    : VideoHandler
      vendor_id       :     
      encoder         : H.264
      timecode        : 01:00:00:00
  Stream #0:1[0x2]: Audio: pcm_s16le (lpcm / 0x6D63706C), 48000 Hz, stereo, s16, 1536 kb/s (default)
    Metadata:
      creation_time   : 2022-05-14T22:52:41.000000Z
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](eng): Data: none (tmcd / 0x64636D74), 0 kb/s
    Metadata:
      creation_time   : 2022-05-14T22:52:41.000000Z
      handler_name    : TimeCodeHandler
      timecode        : 01:00:00:00
Multiple -pix_fmt options specified for stream 0, only the last option '-pix_fmt yuva420p' will be used.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
Incompatible pixel format 'yuva420p' for codec 'png', auto-selecting format 'rgba'
[mp4 @ 0x55ef4a20ed80] Could not find tag for codec pcm_s16le in stream #1, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 -- 
Conversion failed!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.8/lib/python3.8/site-packages/nextcord/ext/commands/core.py", line 168, in wrapped
    ret = await coro(*args, **kwargs)
  File "/mediaforge/cog_media.py", line 39, in reencode
    await improcess(ctx, improcessing.allreencode, [["VIDEO", "IMAGE", "AUDIO"]])
  File "/mediaforge/mainutils.py", line 401, in improcess
    raise e
  File "/mediaforge/mainutils.py", line 350, in improcess
    files[i] = await improcessing.ensuresize(ctx, file, config.min_size, config.max_size)
  File "/mediaforge/improcessing.py", line 1176, in ensuresize
    file = await resize(file, maxsize, "-1")
  File "/mediaforge/improcessing.py", line 1307, in resize
    await run_command("ffmpeg", "-i", image, "-pix_fmt", "yuva420p", "-max_muxing_queue_size", "9999", "-sws_flags",
  File "/mediaforge/improcessing.py", line 101, in run_command
    raise CMDError(f"Command {args} failed.") from CMDError(result)
improcessing.CMDError: Command ('ffmpeg', '-i', 'temp/tBnVSsME.mov', '-pix_fmt', 'yuva420p', '-max_muxing_queue_size', '9999', '-sws_flags', 'spline+accurate_rnd+full_chroma_int+full_chroma_inp+bitexact', '-vf', "scale='1500:-1',setsar=1:1", '-c:v', 'png', '-pix_fmt', 'yuva420p', '-c:a', 'copy', 'temp/lMhAnAMp.mp4') failed.
```

**Comment by Qoft** [comment]
bump

**Comment by HexCodeFFF** [comment]
My bad I've been super busy

**Comment by Qoft** [comment]
might not be a permanent solution but what i did was use a old docker image of mine and then pressing 3 and updating everything

**Comment by HexCodeFFF** [comment]
Hmm that's weird

Using option 3 should pull the latest code from github

**Comment by HexCodeFFF** [comment]
ok whatever weird fucking video file you got ffmpeg wont put into its imaginary container so I'm going to mark this as wontfix
